export const BUSINESS_CATEGORIES = [
  "Accountant", "Auto Repair", "Bakery", "Barber Shop", "Car Wash",
  "Carpet Cleaning", "Chiropractor", "Cleaning Service", "Contractor",
  "Day Care", "Dentist", "Dog Groomer", "Electrician", "Event Planner",
  "Financial Advisor", "Fitness Trainer", "Florist", "Graphic Designer",
  "Handyman", "HVAC", "Insurance Agent", "Interior Designer",
  "Jeweler", "Landscaping", "Laundromat", "Lawn Care", "Locksmith",
  "Massage Therapist", "Mechanic", "Moving Company", "Nail Salon",
  "Notary", "Optometrist", "Painter", "Pest Control", "Pet Grooming",
  "Photographer", "Plumber", "Pool Service", "Pressure Washing",
  "Property Manager", "Real Estate Agent", "Restaurant", "Roofer",
  "Security Company", "Tattoo Shop", "Tax Preparer", "Therapist",
  "Tow Truck", "Tree Service", "Tutor", "Veterinarian", "Wedding Planner",
  "Window Cleaning", "Yoga Studio",
];

export const US_CITIES = [
  "New York, NY", "Los Angeles, CA", "Chicago, IL", "Houston, TX",
  "Phoenix, AZ", "Philadelphia, PA", "San Antonio, TX", "San Diego, CA",
  "Dallas, TX", "Austin, TX", "Jacksonville, FL", "San Jose, CA",
  "Fort Worth, TX", "Columbus, OH", "Charlotte, NC", "Indianapolis, IN",
  "San Francisco, CA", "Seattle, WA", "Denver, CO", "Nashville, TN",
  "Oklahoma City, OK", "El Paso, TX", "Washington, DC", "Boston, MA",
  "Las Vegas, NV", "Portland, OR", "Memphis, TN", "Louisville, KY",
  "Baltimore, MD", "Milwaukee, WI", "Albuquerque, NM", "Tucson, AZ",
  "Fresno, CA", "Sacramento, CA", "Mesa, AZ", "Kansas City, MO",
  "Atlanta, GA", "Omaha, NE", "Colorado Springs, CO", "Raleigh, NC",
  "Miami, FL", "Tampa, FL", "Orlando, FL", "Minneapolis, MN",
  "Cleveland, OH", "New Orleans, LA", "Honolulu, HI", "Savannah, GA",
  "Buford, GA", "Charleston, SC", "Boise, ID", "Richmond, VA",
  "Scottsdale, AZ", "Plano, TX", "Frisco, TX", "Gilbert, AZ",
  "Chandler, AZ", "St. Petersburg, FL", "Laredo, TX", "Durham, NC",
  "Irvine, CA", "Chesapeake, VA", "Garland, TX", "Irving, TX",
  "Hialeah, FL", "Fremont, CA", "Baton Rouge, LA", "Des Moines, IA",
  "Spokane, WA", "Tacoma, WA", "San Bernardino, CA", "Modesto, CA",
];
